// GENERATED BY pif. DO NOT EDIT.
import 'core/plugin.dart';
import 'widgets/agent_console/agent_console.dart';
import 'widgets/diff_viewer/diff_viewer.dart';
import 'widgets/session_rail/session_rail.dart';
import 'widgets/status_bar/status_bar.dart';
import 'widgets/terminal/terminal.dart';
import 'widgets/widget_store/widget_store.dart';

final Map<String, PifWidgetPlugin Function()> pifWidgetFactories = {
  'agent_console': () => AgentConsolePlugin(),
  'diff_viewer': () => DiffViewerPlugin(),
  'session_rail': () => SessionRailPlugin(),
  'status_bar': () => StatusBarPlugin(),
  'terminal': () => TerminalPlugin(),
  'widget_store': () => WidgetStorePlugin(),
};
