import * as crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { pathToFileURL } from "node:url";

export const PIF_PROTOCOL_VERSION = 1 as const;
export const PIF_DEFAULT_PORT = 31415;
export const PIF_CHANNELS = ["session", "widget", "store", "models", "tracker", "shell"] as const;
export type PifChannel = (typeof PIF_CHANNELS)[number];

export interface PifEnvelope<T = unknown> {
	v: 1;
	id: string;
	ts: string;
	channel: `${PifChannel}/${string}`;
	type: string;
	payload: T;
}

export interface PifWidgetManifest {
	id: string;
	name: string;
	version: string;
	description: string;
	slot: "left" | "center" | "right" | "bottom" | "status";
	core: boolean;
	tags: string[];
	dart_dependencies: string[];
}

/** Provenance of a widget under the layered source model (settled app-builder
 * spec, Task #154): `base` = the running app's own widgets and its local
 * archive catalog, `catalog` = the shared global catalog (`~/.pi/pif/catalog/`),
 * `project` = the workspace overlay (`pif_app/widgets/`). A later layer
 * shadows an earlier id wholesale: project > catalog > base. */
export type PifWidgetSource = "base" | "catalog" | "project";

export function createEnvelope<T>(channel: PifEnvelope["channel"], type: string, payload: T, id = crypto.randomUUID()): PifEnvelope<T> {
	if (!PIF_CHANNELS.includes(channel.split("/")[0] as PifChannel)) throw new Error(`Unsupported pif channel: ${channel}`);
	if (!type.trim()) throw new Error("Envelope type is required");
	return { v: PIF_PROTOCOL_VERSION, id, ts: new Date().toISOString(), channel, type, payload };
}

export function decodeEnvelope(raw: string | Buffer): PifEnvelope {
	let value: unknown;
	try { value = JSON.parse(raw.toString()); } catch { throw new Error("Invalid pif JSON envelope"); }
	if (!value || typeof value !== "object") throw new Error("Invalid pif envelope");
	const env = value as Record<string, unknown>;
	if (env.v !== PIF_PROTOCOL_VERSION || typeof env.id !== "string" || typeof env.ts !== "string" || typeof env.channel !== "string" || typeof env.type !== "string" || !("payload" in env)) {
		throw new Error("Invalid pif envelope shape");
	}
	if (!PIF_CHANNELS.includes(env.channel.split("/")[0] as PifChannel)) throw new Error(`Unsupported pif channel: ${env.channel}`);
	return env as unknown as PifEnvelope;
}

function scalar(value: string): string {
	const trimmed = value.trim();
	if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) return trimmed.slice(1, -1);
	return trimmed;
}

export function parseWidgetManifest(raw: string): PifWidgetManifest {
	const values: Record<string, string> = {};
	for (const source of raw.split(/\r?\n/)) {
		const line = source.replace(/\s+#.*$/, "").trim();
		if (!line || line.startsWith("#")) continue;
		const at = line.indexOf(":");
		if (at > 0) values[line.slice(0, at).trim()] = line.slice(at + 1).trim();
	}
	const required = ["id", "name", "version", "description", "slot", "core"];
	for (const key of required) if (!values[key]) throw new Error(`widget.yaml missing ${key}`);
	const id = scalar(values.id);
	if (!/^[a-z][a-z0-9_]*$/.test(id)) throw new Error("Widget id must be lowercase snake_case");
	const slot = scalar(values.slot) as PifWidgetManifest["slot"];
	if (!["left", "center", "right", "bottom", "status"].includes(slot)) throw new Error(`Invalid widget slot: ${slot}`);
	const list = (source = "") => {
		const text = source.trim();
		if (!text || text === "[]") return [];
		if (!text.startsWith("[") || !text.endsWith("]")) throw new Error(`Expected YAML inline list: ${source}`);
		return text.slice(1, -1).split(",").map((entry) => scalar(entry)).filter(Boolean);
	};
	return {
		id,
		name: scalar(values.name),
		version: scalar(values.version),
		description: scalar(values.description),
		slot,
		core: scalar(values.core) === "true",
		tags: list(values.tags),
		dart_dependencies: list(values.dart_dependencies),
	};
}

export function widgetClassName(id: string): string {
	return id.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("") + "Plugin";
}

export function generateWidgetRegistry(manifests: PifRegistryEntry[]): string {
	const sorted = [...manifests].sort((a, b) => a.id.localeCompare(b.id));
	const imports = sorted.map((m) => `import '${registryImportPath(m)}';`).join("\n");
	const factories = sorted.map((m) => `${m.source ? `    // source: ${m.source}\n` : ""}    '${m.id}': () => ${widgetClassName(m.id)}(),`).join("\n");
	return `// GENERATED BY pif. DO NOT EDIT.\nimport 'core/plugin.dart';\n${imports}\n\nMap<String, PifWidgetPlugin Function()> pifWidgetFactories() {\n  return {\n${factories}\n  };\n}\n`;
}

/** Registry codegen input: a manifest plus its resolved source layer. Base
 * widgets import through the app package convention; project overlay widgets
 * live outside the app package and carry an explicit `importPath` (a `file:`
 * URI) so the single generated registry reflects the shadowed winner. */
export interface PifRegistryEntry extends PifWidgetManifest { source?: PifWidgetSource; importPath?: string; }

function registryImportPath(entry: PifRegistryEntry): string {
	const value = entry.importPath ?? `widgets/${entry.id}/${entry.id}.dart`;
	if (value.startsWith("/") || !/^[^'"\\\s]+$/.test(value)) throw new Error(`Unsafe registry import path for ${entry.id}: ${value}`);
	return value;
}

/** Dart import URI for a file outside the app package (project overlay
 * widgets): a `file:` URI is the only form the analyzer resolves from inside
 * the app package, and it keeps the single registry contract intact. Throws
 * on paths that cannot be embedded safely in generated Dart. */
export function dartFileUri(filePath: string): string {
	const uri = pathToFileURL(path.resolve(filePath)).href;
	if (!/^[^'"\\\s]+$/.test(uri)) throw new Error(`Unsafe Dart import URI: ${filePath}`);
	return uri;
}

export function assertSafeWidgetPath(root: string, candidate: string): string {
	const resolvedRoot = path.resolve(root);
	const resolved = path.resolve(candidate);
	if (resolved !== resolvedRoot && !resolved.startsWith(`${resolvedRoot}${path.sep}`)) throw new Error(`Path escapes pif widget boundary: ${candidate}`);
	return resolved;
}

export interface PifBoardColumn { id: string; name: string; state?: "open" | "closed"; label?: string; status?: "any" | "none"; }
export interface PifBoardConfig { columns: PifBoardColumn[]; }
export interface PifTrackerCard { number: number; title: string; type: "epic" | "sprint" | "task" | "issue"; state: "open" | "closed"; labels: string[]; body: string; updatedAt: string; url: string; column: string; parent: number | null; excerpt: string; }

/** Parent link for a card, parsed from its body Reference Index (`Epic: #12`,
 * `Sprint**: #34` — markdown bold tolerated). A task binds to its sprint when
 * exactly one is referenced, else its epic; a sprint binds to its epic.
 * Ambiguity (two different references at the same level) resolves to null —
 * never a guess (#188). */
export function trackerParentRef(body: string, type: string): number | null {
	if (type === "epic" || type === "issue") return null;
	const distinct = (pattern: RegExp): number[] => [...new Set([...body.matchAll(pattern)].map((m) => Number(m[1])))];
	const epics = distinct(/epic\*{0,2}\s*:\s*#?(\d+)/gi);
	const sprints = distinct(/sprint\*{0,2}\s*:\s*#?(\d+)/gi);
	if (type === "sprint") return sprints.length === 1 ? sprints[0] : epics.length === 1 ? epics[0] : null;
	if (sprints.length === 1) return sprints[0];
	if (sprints.length === 0 && epics.length === 1) return epics[0];
	return null;
}

/** Tag→label diff for a ticket update (#189): `desired` is the full tag list
 * from the Attributes pane; `status:*` labels and the card's type label are
 * mechanical and always preserved. Returns the gh label add/remove plan. */
export function plannedLabelChange(current: string[], desired: string[], type?: string): { add: string[]; remove: string[] } {
	const keep = new Set([...current.filter((l) => l.startsWith("status:")), ...(type ? [type] : [])]);
	const want = new Set(desired.map((l) => l.trim()).filter(Boolean));
	const add = [...want].filter((l) => !current.includes(l) && !keep.has(l));
	const remove = current.filter((l) => !want.has(l) && !keep.has(l));
	return { add, remove };
}

/** Plain-text card excerpt for the board preview (#188): fenced code removed,
 * markdown stripped, the Reference Index section skipped, first meaningful
 * paragraph(s) kept up to `cap` characters with an ellipsis. */
export function trackerExcerpt(body: string, cap = 240): string {
	const lines = body.replace(/```[\s\S]*?```/g, " ").split(/\r?\n/);
	const paragraphs: string[] = [];
	let current = "";
	let inReference = false;
	for (const raw of lines) {
		const line = raw.trim();
		if (/^#{1,6}\s/.test(line)) {
			if (current) { paragraphs.push(current); current = ""; }
			inReference = /reference index/i.test(line);
			continue;
		}
		if (inReference) continue;
		if (!line) {
			if (current) { paragraphs.push(current); current = ""; }
			continue;
		}
		const text = line.replace(/!\[[^\]]*\]\([^)]*\)/g, "").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1").replace(/[*_`#>]+/g, "").trim();
		if (text) current = current ? `${current} ${text}` : text;
	}
	if (current) paragraphs.push(current);
	const text = paragraphs.join(" ").replace(/\s+/g, " ").trim();
	if (text.length <= cap) return text;
	const cut = text.slice(0, cap);
	return `${cut.slice(0, Math.min(cut.length, cut.lastIndexOf(" ") > 0 ? cut.lastIndexOf(" ") : cut.length))}…`;
}

/** Repo-versioned board definition (`.pif/board.yaml`): a `column <id>:` block
 * per column with `name`, an optional `state` (open|closed), an optional exact
 * `label` to match and write back, and `status: any|none` for presence of any
 * `status:*` label. The first column whose rules all hold claims the card. */
export function parseBoardConfig(raw: string): PifBoardConfig {
	const columns: PifBoardColumn[] = [];
	let current: PifBoardColumn | null = null;
	for (const source of raw.split(/\r?\n/)) {
		const line = source.replace(/\s+#.*$/, "");
		if (!line.trim() || line.trim().startsWith("#")) continue;
		const header = /^column\s+([a-z][a-z0-9_-]*)\s*:\s*$/.exec(line.trim());
		if (header) { current = { id: header[1], name: "" }; columns.push(current); continue; }
		const at = line.indexOf(":");
		const key = at > 0 ? line.slice(0, at).trim() : "";
		if (!/^[\w-]+$/.test(key)) throw new Error(`Unexpected board.yaml line: ${line.trim()}`);
		if (!current) throw new Error("board.yaml properties must follow a column header");
		const value = scalar(line.slice(at + 1));
		if (key === "name") current.name = value;
		else if (key === "state") { if (value !== "open" && value !== "closed") throw new Error(`Invalid column state: ${value}`); current.state = value; }
		else if (key === "label") current.label = value;
		else if (key === "status") { if (value !== "any" && value !== "none") throw new Error(`Invalid column status rule: ${value}`); current.status = value; }
		else throw new Error(`Unknown board.yaml column key: ${key}`);
	}
	if (!columns.length) throw new Error("board.yaml requires at least one column");
	for (const column of columns) {
		if (!column.name) throw new Error(`Column ${column.id} is missing a name`);
		if (columns.filter((candidate) => candidate.id === column.id).length > 1) throw new Error(`Duplicate column id: ${column.id}`);
	}
	return { columns };
}

/** Zero-config board for repos without `.pif/board.yaml`. */
export function defaultBoardConfig(): PifBoardConfig {
	return { columns: [
		{ id: "backlog", name: "Backlog", state: "open", status: "none" },
		{ id: "in_progress", name: "In Progress", state: "open", status: "any" },
		{ id: "done", name: "Done", state: "closed" },
	] };
}

export function columnForCard(labels: string[], state: string, config: PifBoardConfig): string {
	for (const column of config.columns) {
		if (column.state && column.state !== state) continue;
		if (column.label && !labels.includes(column.label)) continue;
		if (column.status === "any" && !labels.some((label) => label.startsWith("status:"))) continue;
		if (column.status === "none" && labels.some((label) => label.startsWith("status:"))) continue;
		return column.id;
	}
	return config.columns[0].id;
}

const TRACKER_TYPES = ["epic", "sprint", "task"] as const;

export function normalizeGhIssue(issue: any, config: PifBoardConfig): PifTrackerCard {
	const labels = Array.isArray(issue.labels) ? issue.labels.map((label: any) => String(label?.name ?? label)).filter(Boolean) : [];
	const type = TRACKER_TYPES.find((candidate) => labels.includes(candidate)) ?? "issue";
	const state = String(issue.state ?? "").toLowerCase() === "closed" ? "closed" : "open";
	return { number: Number(issue.number), title: String(issue.title ?? ""), type, state, labels, body: String(issue.body ?? "").slice(0, 20_000), updatedAt: String(issue.updatedAt ?? ""), url: String(issue.url ?? ""), column: columnForCard(labels, state, config), parent: trackerParentRef(String(issue.body ?? ""), type), excerpt: trackerExcerpt(String(issue.body ?? "")) };
}

/** Write-back plan for dropping a card on a column: ensure the column's exact
 * label, clear competing `status:*` labels, and land in the column's state. */
export function plannedTrackerMove(card: PifTrackerCard, column: PifBoardColumn): { add: string[]; remove: string[]; state: "open" | "closed" } {
	const remove = card.labels.filter((candidate) => candidate.startsWith("status:") && candidate !== column.label);
	const add = column.label && !card.labels.includes(column.label) ? [column.label] : [];
	return { add, remove, state: column.state === "closed" ? "closed" : "open" };
}

export interface TrackerState { repo: string | null; columns: { id: string; name: string }[]; cards: PifTrackerCard[]; stale: boolean; fetchedAt: string | null; error: string | null; }
export type SpawnRunner = (command: string, args: string[], options: { cwd: string; timeout: number }) => { status: number | null; stdout: string; stderr: string };

const trackerRunner: SpawnRunner = (command, args, options) => { const result = spawnSync(command, args, { ...options, encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }); return { status: result.status, stdout: result.stdout ?? "", stderr: result.stderr ?? "" }; };

/** Board data for the tracker widget: reads the workspace repo's issues via
 * the ambient gh session, writes card moves back per the repo's board rules
 * (`.pif/board.yaml`, default board when absent), and caches to SQLite (JSON
 * fallback) so the board stays readable when the tracker is unreachable. */
export class TrackerSync {
	readonly state: TrackerState = { repo: null, columns: [], cards: [], stale: true, fetchedAt: null, error: null };
	private workspace: string;
	private changed: (state: TrackerState) => void;
	private runner: SpawnRunner;
	private preferJsonCache: boolean;
	private repoCache: string | null | undefined;
	private timer: NodeJS.Timeout | null = null;
	private db: any = null; private jsonPath = "";
	constructor(workspace: string, changed: (state: TrackerState) => void, runner: SpawnRunner = trackerRunner, preferJsonCache = false) {
		this.workspace = workspace; this.changed = changed; this.runner = runner; this.preferJsonCache = preferJsonCache;
	}
	async init() {
		const cacheDir = path.join(this.workspace, ".pi", "pif", "cache");
		if (!this.preferJsonCache) {
			try {
				const { DatabaseSync } = await import("node:sqlite");
				fs.mkdirSync(cacheDir, { recursive: true });
				this.db = new DatabaseSync(path.join(cacheDir, "tracker.db"));
				this.db.exec("CREATE TABLE IF NOT EXISTS tracker (id INTEGER PRIMARY KEY, repo TEXT, fetched_at TEXT, cards TEXT)");
			} catch { this.db = null; }
		}
		this.jsonPath = path.join(cacheDir, "tracker-cache.json");
		this.loadCache();
	}
	start() { const kick = setTimeout(() => this.refresh(), 250); kick.unref?.(); this.timer = setInterval(() => this.refresh(), 300_000); this.timer.unref?.(); }
	stop() { if (this.timer) clearInterval(this.timer); this.timer = null; }
	private ghBin() { return process.env.PIF_GH_BIN || "gh"; }
	private boardPath() { return path.join(this.workspace, ".pif", "board.yaml"); }
	private boardConfig(): PifBoardConfig { try { return parseBoardConfig(fs.readFileSync(this.boardPath(), "utf8")); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return defaultBoardConfig(); throw error; } }
	private columnNames(config: PifBoardConfig) { return config.columns.map(({ id, name }) => ({ id, name })); }
	private resolveRepo(): string | null {
		if (this.repoCache !== undefined) return this.repoCache;
		const git = this.runner("git", ["remote", "get-url", "origin"], { cwd: this.workspace, timeout: 10_000 });
		const match = git.status === 0 ? /github\.com[/:]([^/\s]+)\/([^/\s]+?)(?:\.git)?\s*$/.exec(git.stdout.trim()) : null;
		this.repoCache = match ? `${match[1]}/${match[2]}` : null;
		return this.repoCache;
	}
	refresh(): { ok: boolean; error?: string } {
		let config: PifBoardConfig;
		try { config = this.boardConfig(); } catch (error) { this.state.error = `Invalid board.yaml: ${String((error as Error).message)}`; this.changed(this.state); return { ok: false, error: this.state.error }; }
		const repo = this.resolveRepo();
		if (!repo) { this.state.error = "Workspace has no GitHub origin remote"; this.state.stale = true; this.changed(this.state); return { ok: false, error: this.state.error }; }
		const list = this.runner(this.ghBin(), ["issue", "list", "-R", repo, "--state", "all", "--limit", "300", "--json", "number,title,state,labels,updatedAt,url,body"], { cwd: this.workspace, timeout: 30_000 });
		this.state.repo = repo; this.state.columns = this.columnNames(config);
		if (list.status !== 0) {
			this.state.stale = true; this.state.error = `${list.stderr || list.stdout}`.trim() || "gh issue list failed";
			this.changed(this.state); return { ok: false, error: this.state.error };
		}
		let issues: any[] = []; try { const parsed = JSON.parse(list.stdout); if (Array.isArray(parsed)) issues = parsed; } catch { /* empty board */ }
		this.state.cards = issues.map((issue) => normalizeGhIssue(issue, config)).sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)));
		this.state.stale = false; this.state.fetchedAt = new Date().toISOString(); this.state.error = null;
		this.writeCache(); this.changed(this.state);
		return { ok: true };
	}
	move(params: any): { ok: boolean; number?: number; column?: string; error?: string } {
		const number = Number(params.number); const columnId = String(params.column ?? "");
		const card = this.state.cards.find((candidate) => candidate.number === number);
		if (!card) return { ok: false, error: `Unknown card #${number}` };
		let config: PifBoardConfig; try { config = this.boardConfig(); } catch (error) { return { ok: false, error: `Invalid board.yaml: ${String((error as Error).message)}` }; }
		const column = config.columns.find((candidate) => candidate.id === columnId);
		if (!column) return { ok: false, error: `Unknown column: ${columnId}` };
		const repo = this.state.repo ?? this.resolveRepo();
		if (!repo) return { ok: false, error: "Workspace has no GitHub origin remote" };
		const plan = plannedTrackerMove(card, column);
		if (plan.add.length || plan.remove.length) {
			const args = ["issue", "edit", String(number), "-R", repo];
			for (const label of plan.add) args.push("--add-label", label);
			for (const label of plan.remove) args.push("--remove-label", label);
			const edit = this.runner(this.ghBin(), args, { cwd: this.workspace, timeout: 30_000 });
			if (edit.status !== 0) return { ok: false, error: `${edit.stderr || edit.stdout}`.trim() || "gh issue edit failed" };
		}
		if (plan.state !== card.state) {
			const flip = this.runner(this.ghBin(), ["issue", plan.state === "closed" ? "close" : "reopen", String(number), "-R", repo], { cwd: this.workspace, timeout: 30_000 });
			if (flip.status !== 0) return { ok: false, error: `${flip.stderr || flip.stdout}`.trim() || `gh issue ${plan.state} failed` };
		}
		card.labels = [...card.labels.filter((label) => !plan.remove.includes(label)), ...plan.add];
		card.state = plan.state; card.column = columnForCard(card.labels, card.state, config);
		this.writeCache(); this.changed(this.state);
		return { ok: true, number, column: columnId };
	}
	list() { return { repo: this.state.repo, columns: this.state.columns, stale: this.state.stale, fetchedAt: this.state.fetchedAt, error: this.state.error, cards: this.state.cards.map(({ body, ...card }) => card) }; }
	create(params: any): { ok: boolean; number?: number; error?: string } {
		const title = String(params.title ?? "").trim(); if (!title) return { ok: false, error: "Title is required" };
		const type = TRACKER_TYPES.find((candidate) => candidate === String(params.type ?? "")) ?? "issue";
		const repo = this.state.repo ?? this.resolveRepo();
		if (!repo) return { ok: false, error: "Workspace has no GitHub origin remote" };
		let config: PifBoardConfig; try { config = this.boardConfig(); } catch (error) { return { ok: false, error: `Invalid board.yaml: ${String((error as Error).message)}` }; }
		const column = params.column !== undefined && params.column !== null && String(params.column) !== "" ? config.columns.find((candidate) => candidate.id === String(params.column)) : undefined;
		if (params.column && !column) return { ok: false, error: `Unknown column: ${params.column}` };
		const labels = [...(type === "issue" ? [] : [type]), ...(column?.label ? [column.label] : [])];
		const run = (withLabels: boolean) => {
			const args = ["issue", "create", "-R", repo, "--title", title, "--body", String(params.body ?? "")];
			if (withLabels) for (const label of labels) args.push("--label", label);
			return this.runner(this.ghBin(), args, { cwd: this.workspace, timeout: 30_000 });
		};
		let created = run(labels.length > 0);
		if (created.status !== 0 && labels.length > 0) created = run(false);
		if (created.status !== 0) return { ok: false, error: `${created.stderr || created.stdout}`.trim() || "gh issue create failed" };
		const number = Number(/issues\/(\d+)/.exec(created.stdout)?.[1] ?? 0);
		if (!number) return { ok: false, error: `Could not parse the created issue number: ${created.stdout.trim()}` };
		const card: PifTrackerCard = { number, title, type, state: "open", labels, body: String(params.body ?? "").slice(0, 20_000), updatedAt: new Date().toISOString(), url: `https://github.com/${repo}/issues/${number}`, column: columnForCard(labels, "open", config) };
		this.state.cards = [card, ...this.state.cards]; this.writeCache(); this.changed(this.state);
		return { ok: true, number };
	}
	update(params: any): { ok: boolean; number?: number; error?: string } {
		const number = Number(params.number);
		const card = this.state.cards.find((candidate) => candidate.number === number);
		if (!card) return { ok: false, error: `Unknown card #${number}` };
		const title = params.title !== undefined ? String(params.title).trim() : undefined;
		if (title !== undefined && !title) return { ok: false, error: "Title cannot be empty" };
		const body = params.body !== undefined ? String(params.body) : undefined;
		const wantsLabelChange = Array.isArray(params.labels) && plannedLabelChange(card.labels, params.labels.map(String), card.type).add.length + plannedLabelChange(card.labels, params.labels.map(String), card.type).remove.length > 0;
		if (title === undefined && body === undefined && !wantsLabelChange) return { ok: false, error: "Nothing to update" };
		const repo = this.state.repo ?? this.resolveRepo();
		if (!repo) return { ok: false, error: "Workspace has no GitHub origin remote" };
		const args = ["issue", "edit", String(number), "-R", repo];
		if (title !== undefined) args.push("--title", title);
		if (body !== undefined) args.push("--body", body);
		const labelPlan = Array.isArray(params.labels) ? plannedLabelChange(card.labels, params.labels.map(String), card.type) : null;
		if (labelPlan) {
			for (const label of labelPlan.add) args.push("--add-label", label);
			for (const label of labelPlan.remove) args.push("--remove-label", label);
		}
		if (title === undefined && body === undefined && (!labelPlan || (!labelPlan.add.length && !labelPlan.remove.length))) return { ok: false, error: "Nothing to update" };
		const edit = this.runner(this.ghBin(), args, { cwd: this.workspace, timeout: 30_000 });
		if (edit.status !== 0) return { ok: false, error: `${edit.stderr || edit.stdout}`.trim() || "gh issue edit failed" };
		if (title !== undefined) card.title = title;
		if (body !== undefined) card.body = body.slice(0, 20_000);
		if (labelPlan) card.labels = [...card.labels.filter((l) => !labelPlan.remove.includes(l) || l.startsWith("status:") || l === card.type), ...labelPlan.add];
		card.updatedAt = new Date().toISOString();
		this.writeCache(); this.changed(this.state);
		return { ok: true, number };
	}
	delete(params: any): { ok: boolean; number?: number; error?: string } {
		const number = Number(params.number);
		const card = this.state.cards.find((candidate) => candidate.number === number);
		if (!card) return { ok: false, error: `Unknown card #${number}` };
		const repo = this.state.repo ?? this.resolveRepo();
		if (!repo) return { ok: false, error: "Workspace has no GitHub origin remote" };
		const removed = this.runner(this.ghBin(), ["issue", "delete", String(number), "-R", repo, "--yes"], { cwd: this.workspace, timeout: 30_000 });
		if (removed.status !== 0) return { ok: false, error: `${removed.stderr || removed.stdout}`.trim() || "gh issue delete failed" };
		this.state.cards = this.state.cards.filter((candidate) => candidate.number !== number);
		this.writeCache(); this.changed(this.state);
		return { ok: true, number };
	}
	private loadCache() {
		if (this.db) {
			try { const row = this.db.prepare("SELECT repo, fetched_at, cards FROM tracker WHERE id = 1").get(); if (row) { this.applyCache(String(row.repo ?? "") || null, String(row.fetched_at ?? "") || null, JSON.parse(String(row.cards ?? "[]"))); return; } } catch { /* fall through to json */ }
		}
		try { const parsed = JSON.parse(fs.readFileSync(this.jsonPath, "utf8")); this.applyCache(parsed.repo ?? null, parsed.fetchedAt ?? null, Array.isArray(parsed.cards) ? parsed.cards : []); } catch { /* absent */ }
	}
	private applyCache(repo: string | null, fetchedAt: string | null, cards: any[]) {
		if (!Array.isArray(cards) || !cards.length) return;
		this.state.repo = repo; this.state.cards = cards; this.state.fetchedAt = fetchedAt; this.state.stale = true;
		if (!this.state.columns.length) this.state.columns = this.columnNames(defaultBoardConfig());
	}
	private writeCache() {
		if (this.db) { this.db.prepare("INSERT INTO tracker (id, repo, fetched_at, cards) VALUES (1, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET repo = excluded.repo, fetched_at = excluded.fetched_at, cards = excluded.cards").run(this.state.repo, this.state.fetchedAt, JSON.stringify(this.state.cards)); return; }
		fs.mkdirSync(path.dirname(this.jsonPath), { recursive: true }); fs.writeFileSync(this.jsonPath, JSON.stringify({ repo: this.state.repo, fetchedAt: this.state.fetchedAt, cards: this.state.cards }, null, 2) + "\n");
	}
}

const CHILD_SCRUBBED_ENV_KEYS = ["PIF_AUTOSTART", "PIF_NO_FLUTTER", "PIF_PORT", "PIF_TOKEN", "PIF_ALLOWED_ORIGINS"] as const;

/** Environment for spawned child sessions: hub lifecycle vars must not
 * propagate, or every child tries to autostart a second hub on our port.
 * Credentials (PIF_TOKEN, PIF_ALLOWED_ORIGINS) are scrubbed so a
 * prompt-injected child cannot open an authenticated hub connection. */
export function childEnvironment(env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
	const child = { ...env };
	for (const key of CHILD_SCRUBBED_ENV_KEYS) delete child[key];
	return child;
}

export function extractPifToken(requestUrl: string): string | null {
	const query = requestUrl.split("?")[1] ?? "";
	for (const pair of query.split("&")) {
		const at = pair.indexOf("=");
		if (at <= 0) continue;
		let key: string, value: string;
		try { key = decodeURIComponent(pair.slice(0, at)); value = decodeURIComponent(pair.slice(at + 1)); } catch { return null; }
		if (key === "token") return value;
	}
	return null;
}

/** Hub upgrade authorization: a per-launch token is always required, and a
 * browser-supplied Origin (the Dart WebSocket client sends none) must be
 * explicitly allowlisted via PIF_ALLOWED_ORIGINS. */
export function pifUpgradeAuthorized(requestUrl: string, origin: string | undefined, token: string, allowedOrigins: readonly string[] = []): boolean {
	if (origin !== undefined && !allowedOrigins.includes(origin)) return false;
	const provided = extractPifToken(requestUrl);
	if (!provided || provided.length !== token.length) return false;
	return crypto.timingSafeEqual(Buffer.from(provided), Buffer.from(token));
}

/** Identity proof for the HTTP health probe: the hub answers a caller
 * nonce with an HMAC-SHA256 under the hub token, so the app only treats a
 * listener as *its* hub when it proves token possession — a port squatter
 * that merely echoes `"name":"pif"` cannot harvest the real token or the
 * user's first typed prompt. */
export function pifProbeProof(nonce: string, token: string): string {
	return crypto.createHmac("sha256", token).update(nonce).digest("hex");
}

export function pifProbeValid(nonce: string, token: string, proof: unknown): boolean {
	if (typeof proof !== "string" || proof.length !== 64) return false;
	const expected = Buffer.from(pifProbeProof(nonce, token));
	const provided = Buffer.from(proof);
	return expected.length === provided.length && crypto.timingSafeEqual(expected, provided);
}

export const __test = { scalar };
