import * as crypto from "node:crypto";
import * as path from "node:path";

export const PIF_PROTOCOL_VERSION = 1 as const;
export const PIF_DEFAULT_PORT = 31415;
export const PIF_CHANNELS = ["session", "widget", "store", "shell", "models"] as const;
export type PifChannel = (typeof PIF_CHANNELS)[number];

export interface PifEnvelope<T = unknown> {
	v: 1;
	id: string;
	ts: string;
	channel: `${PifChannel}/${string}`;
	type: string;
	payload: T;
}

export interface PifWidgetManifest {
	id: string;
	name: string;
	version: string;
	description: string;
	slot: "left" | "center" | "right" | "bottom" | "status";
	core: boolean;
	tags: string[];
	dart_dependencies: string[];
}

export function createEnvelope<T>(channel: PifEnvelope["channel"], type: string, payload: T, id = crypto.randomUUID()): PifEnvelope<T> {
	if (!PIF_CHANNELS.includes(channel.split("/")[0] as PifChannel)) throw new Error(`Unsupported pif channel: ${channel}`);
	if (!type.trim()) throw new Error("Envelope type is required");
	return { v: PIF_PROTOCOL_VERSION, id, ts: new Date().toISOString(), channel, type, payload };
}

export function decodeEnvelope(raw: string | Buffer): PifEnvelope {
	let value: unknown;
	try { value = JSON.parse(raw.toString()); } catch { throw new Error("Invalid pif JSON envelope"); }
	if (!value || typeof value !== "object") throw new Error("Invalid pif envelope");
	const env = value as Record<string, unknown>;
	if (env.v !== PIF_PROTOCOL_VERSION || typeof env.id !== "string" || typeof env.ts !== "string" || typeof env.channel !== "string" || typeof env.type !== "string" || !("payload" in env)) {
		throw new Error("Invalid pif envelope shape");
	}
	if (!PIF_CHANNELS.includes(env.channel.split("/")[0] as PifChannel)) throw new Error(`Unsupported pif channel: ${env.channel}`);
	return env as unknown as PifEnvelope;
}

function scalar(value: string): string {
	const trimmed = value.trim();
	if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) return trimmed.slice(1, -1);
	return trimmed;
}

export function parseWidgetManifest(raw: string): PifWidgetManifest {
	const values: Record<string, string> = {};
	for (const source of raw.split(/\r?\n/)) {
		const line = source.replace(/\s+#.*$/, "").trim();
		if (!line || line.startsWith("#")) continue;
		const at = line.indexOf(":");
		if (at > 0) values[line.slice(0, at).trim()] = line.slice(at + 1).trim();
	}
	const required = ["id", "name", "version", "description", "slot", "core"];
	for (const key of required) if (!values[key]) throw new Error(`widget.yaml missing ${key}`);
	const id = scalar(values.id);
	if (!/^[a-z][a-z0-9_]*$/.test(id)) throw new Error("Widget id must be lowercase snake_case");
	const slot = scalar(values.slot) as PifWidgetManifest["slot"];
	if (!["left", "center", "right", "bottom", "status"].includes(slot)) throw new Error(`Invalid widget slot: ${slot}`);
	const list = (source = "") => {
		const text = source.trim();
		if (!text || text === "[]") return [];
		if (!text.startsWith("[") || !text.endsWith("]")) throw new Error(`Expected YAML inline list: ${source}`);
		return text.slice(1, -1).split(",").map((entry) => scalar(entry)).filter(Boolean);
	};
	return {
		id,
		name: scalar(values.name),
		version: scalar(values.version),
		description: scalar(values.description),
		slot,
		core: scalar(values.core) === "true",
		tags: list(values.tags),
		dart_dependencies: list(values.dart_dependencies),
	};
}

export function widgetClassName(id: string): string {
	return id.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("") + "Plugin";
}

export function generateWidgetRegistry(manifests: PifWidgetManifest[]): string {
	const sorted = [...manifests].sort((a, b) => a.id.localeCompare(b.id));
	const imports = sorted.map((m) => `import 'widgets/${m.id}/${m.id}.dart';`).join("\n");
	const factories = sorted.map((m) => `    '${m.id}': () => ${widgetClassName(m.id)}(),`).join("\n");
	return `// GENERATED BY pif. DO NOT EDIT.\nimport 'core/plugin.dart';\n${imports}\n\nMap<String, PifWidgetPlugin Function()> pifWidgetFactories() {\n  return {\n${factories}\n  };\n}\n`;
}

export function assertSafeWidgetPath(root: string, candidate: string): string {
	const resolvedRoot = path.resolve(root);
	const resolved = path.resolve(candidate);
	if (resolved !== resolvedRoot && !resolved.startsWith(`${resolvedRoot}${path.sep}`)) throw new Error(`Path escapes pif widget boundary: ${candidate}`);
	return resolved;
}

const CHILD_SCRUBBED_ENV_KEYS = ["PIF_AUTOSTART", "PIF_NO_FLUTTER", "PIF_PORT", "PIF_TOKEN", "PIF_ALLOWED_ORIGINS"] as const;

/** Environment for spawned child sessions: hub lifecycle vars must not
 * propagate, or every child tries to autostart a second hub on our port.
 * Credentials (PIF_TOKEN, PIF_ALLOWED_ORIGINS) are scrubbed so a
 * prompt-injected child cannot open an authenticated hub connection. */
export function childEnvironment(env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
	const child = { ...env };
	for (const key of CHILD_SCRUBBED_ENV_KEYS) delete child[key];
	return child;
}

export function extractPifToken(requestUrl: string): string | null {
	const query = requestUrl.split("?")[1] ?? "";
	for (const pair of query.split("&")) {
		const at = pair.indexOf("=");
		if (at <= 0) continue;
		let key: string, value: string;
		try { key = decodeURIComponent(pair.slice(0, at)); value = decodeURIComponent(pair.slice(at + 1)); } catch { return null; }
		if (key === "token") return value;
	}
	return null;
}

/** Hub upgrade authorization: a per-launch token is always required, and a
 * browser-supplied Origin (the Dart WebSocket client sends none) must be
 * explicitly allowlisted via PIF_ALLOWED_ORIGINS. */
export function pifUpgradeAuthorized(requestUrl: string, origin: string | undefined, token: string, allowedOrigins: readonly string[] = []): boolean {
	if (origin !== undefined && !allowedOrigins.includes(origin)) return false;
	const provided = extractPifToken(requestUrl);
	if (!provided || provided.length !== token.length) return false;
	return crypto.timingSafeEqual(Buffer.from(provided), Buffer.from(token));
}

/** Identity proof for the HTTP health probe: the hub answers a caller
 * nonce with an HMAC-SHA256 under the hub token, so the app only treats a
 * listener as *its* hub when it proves token possession — a port squatter
 * that merely echoes `"name":"pif"` cannot harvest the real token or the
 * user's first typed prompt. */
export function pifProbeProof(nonce: string, token: string): string {
	return crypto.createHmac("sha256", token).update(nonce).digest("hex");
}

export function pifProbeValid(nonce: string, token: string, proof: unknown): boolean {
	if (typeof proof !== "string" || proof.length !== 64) return false;
	const expected = Buffer.from(pifProbeProof(nonce, token));
	const provided = Buffer.from(proof);
	return expected.length === provided.length && crypto.timingSafeEqual(expected, provided);
}

export const __test = { scalar };
