import test from 'node:test';
import assert from 'node:assert/strict';
import childProcess from 'node:child_process';
import { EventEmitter } from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import { syncBuiltinESMExports } from 'node:module';
const repo = path.resolve(import.meta.dirname, '..');
import { __test as __shared, createEnvelope, decodeEnvelope, dartFileUri, generateWidgetRegistry, parseWidgetManifest, assertSafeWidgetPath, childEnvironment, extractPifToken, pifProbeProof, pifProbeValid, pifUpgradeAuthorized } from './pif-shared.ts';
import { parseBoardConfig, defaultBoardConfig, columnForCard, normalizeGhIssue, plannedTrackerMove, TrackerSync, trackerParentRef, trackerExcerpt, plannedLabelChange, parseAppManifest, renderAppManifest, addAppPage, setAppHome, slugifyAppId } from './pif-shared.ts';
import { __test as __pif } from './pif.ts';

const manifest = `id: alpha_widget\nname: "Alpha"\nversion: 0.1.0\ndescription: "Fixture"\nslot: center\ncore: false\ntags: [test, golden]\ndart_dependencies: []\n`;
const tempDir = (prefix) => fs.mkdtempSync(path.join('/tmp', prefix));
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function waitFor(check, message, timeout = 5_000) {
  const started = Date.now();
  while (Date.now() - started < timeout) {
    try {
      const value = await check();
      if (value) return value;
    } catch {}
    await delay(25);
  }
  throw new Error(`Timed out: ${message}`);
}

function makeBuildChild() {
  const child = new EventEmitter();
  child.stdout = new EventEmitter();
  child.stderr = new EventEmitter();
  child.stdin = { write() {}, end() {} };
  child.exitCode = null;
  child.signalCode = null;
  child.killCalls = [];
  child.kill = (signal = 'SIGTERM') => {
    child.killCalls.push(signal);
    child.signalCode = signal;
    return true;
  };
  child.emitSpawn = () => child.emit('spawn');
  child.emitClose = (code = 0, signal = null) => {
    child.exitCode = code;
    child.signalCode = signal;
    child.emit('close', code, signal);
  };
  child.emitError = (error) => child.emit('error', error instanceof Error ? error : new Error(String(error)));
  return child;
}

function patchBuildSpawn(plans) {
  const originalSpawn = childProcess.spawn;
  const harness = { calls: [], children: [], plans: plans.map((plan) => ({...plan})) };
  childProcess.spawn = (command, args) => {
    harness.calls.push({command, args});
    const plan = harness.plans.shift();
    if (!plan) throw new Error(`Unexpected spawn: ${command}`);
    if (plan.kind === 'throw') throw new Error(plan.message);
    const child = makeBuildChild();
    harness.children.push(child);
    if (plan.kind === 'error') {
      queueMicrotask(() => {
        child.emitError(plan.error ?? new Error(plan.message ?? 'spawn failed'));
        queueMicrotask(() => child.emitClose(plan.code ?? 127, plan.signal ?? null));
      });
    }
    return child;
  };
  syncBuiltinESMExports();
  return {
    harness,
    restore() {
      childProcess.spawn = originalSpawn;
      syncBuiltinESMExports();
    },
  };
}

test('pif envelope codec accepts all protocol channels and rejects malformed data', () => {
  for (const channel of ['session/state', 'widget/registry', 'store/catalog', 'models/save', 'tracker/state', 'shell/state', 'app/build']) {
    const env = createEnvelope(channel, 'fixture', {ok: true}, 'fixed');
    assert.deepEqual(decodeEnvelope(JSON.stringify(env)), env);
  }
  assert.throws(() => decodeEnvelope('{"v":2}'), /Invalid pif envelope/);
  assert.throws(() => createEnvelope('network/state', 'bad', {}), /Unsupported/);
});

test('widget manifest parsing validates contract and dependencies', () => {
  const parsed = parseWidgetManifest(manifest.replace('dart_dependencies: []', 'dart_dependencies: [path_provider]'));
  assert.equal(parsed.id, 'alpha_widget');
  assert.deepEqual(parsed.tags, ['test', 'golden']);
  assert.deepEqual(parsed.dart_dependencies, ['path_provider']);
  assert.throws(() => parseWidgetManifest(manifest.replace('slot: center', 'slot: nowhere')), /Invalid widget slot/);
});

test('registry codegen matches deterministic golden', () => {
  const actual = generateWidgetRegistry([parseWidgetManifest(manifest)]);
  assert.equal(actual, `// GENERATED BY pif. DO NOT EDIT.\nimport 'core/plugin.dart';\nimport 'widgets/alpha_widget/alpha_widget.dart';\n\nMap<String, PifWidgetPlugin Function()> pifWidgetFactories() {\n  return {\n    'alpha_widget': () => AlphaWidgetPlugin(),\n  };\n}\n`);
});

test('widget path guard line-stops traversal outside managed roots', () => {
  const root = path.join('/tmp', 'pif', 'lib', 'widgets');
  assert.equal(assertSafeWidgetPath(root, path.join(root, 'safe')), path.join(root, 'safe'));
  assert.throws(() => assertSafeWidgetPath(root, path.join(root, '..', '..', 'main.dart')), /escapes/);
});

test('child environment scrubs hub lifecycle variables and credentials', () => {
  const child = childEnvironment({PIF_AUTOSTART: '1', PIF_NO_FLUTTER: '1', PIF_PORT: '31415', PIF_TOKEN: 'secret-token', PIF_ALLOWED_ORIGINS: 'https://app.local', PIF_PI_BIN: '/fake/pi', PATH: '/usr/bin'});
  assert.equal(child.PIF_AUTOSTART, undefined);
  assert.equal(child.PIF_NO_FLUTTER, undefined);
  assert.equal(child.PIF_PORT, undefined);
  assert.equal(child.PIF_TOKEN, undefined, 'children must not inherit the hub token');
  assert.equal(child.PIF_ALLOWED_ORIGINS, undefined);
  assert.equal(child.PIF_PI_BIN, '/fake/pi');
  assert.equal(child.PATH, '/usr/bin');
});

test('packaged hubs resolve the bundled pi runtime for child sessions', () => {
  const source = fs.readFileSync(path.join(repo, 'extensions', 'pif.ts'), 'utf8');
  assert.match(source, /function resolvePiInvocation\(extensionPath: string\)/);
  assert.match(source, /const resources = path\.resolve\(path\.dirname\(extensionPath\), "\.\."\)/);
  assert.match(source, /spawn\(pi\.command, args/);
  assert.doesNotMatch(source, /spawn\(process\.env\.PIF_PI_BIN \|\| "pi"/);
});

test('malformed percent-encoding in the upgrade URL does not throw', () => {
  const token = 'a'.repeat(64);
  assert.equal(extractPifToken('/pif?token=%zz'), null);
  assert.equal(extractPifToken(`/pif?other=1&token=${token}`), token, 'valid pairs still parse');
});

test('hub upgrade authorization requires token and allowlisted browser origins', () => {
  const token = 'a'.repeat(64);
  assert.equal(extractPifToken('/pif?token=' + token), token);
  assert.equal(extractPifToken('/pif'), null);
  assert.equal(extractPifToken('/pif?other=1'), null);
  assert.equal(pifUpgradeAuthorized('/pif?token=' + token, undefined, token), true);
  assert.equal(pifUpgradeAuthorized('/pif?token=' + 'b'.repeat(64), undefined, token), false);
  assert.equal(pifUpgradeAuthorized('/pif', undefined, token), false);
  assert.equal(pifUpgradeAuthorized('/pif?token=' + token, 'https://evil.example', token), false);
  assert.equal(pifUpgradeAuthorized('/pif?token=' + token, 'https://app.local', token, ['https://app.local']), true);
});

test('probe proof is an HMAC of the nonce under the hub token', async () => {
  const { createHmac } = await import('node:crypto');
  const token = 't'.repeat(64);
  const nonce = 'nonce-value';
  assert.equal(pifProbeProof(nonce, token), createHmac('sha256', token).update(nonce).digest('hex'));
  assert.equal(pifProbeValid(nonce, token, pifProbeProof(nonce, token)), true);
  assert.equal(pifProbeValid(nonce, token, '0'.repeat(64)), false);
  assert.equal(pifProbeValid(nonce, 'other-token', pifProbeProof(nonce, token)), false);
  assert.equal(pifProbeValid(nonce, token, null), false);
  assert.equal(pifProbeValid(nonce, token, undefined), false);
});

test('hub source preserves phase-one process and analyze gates', async () => {
  const source = await import('node:fs/promises').then((fs) => fs.readFile(new URL('./pif.ts', import.meta.url), 'utf8'));
  assert.match(source, /dart[^\n]+analyze/);
  assert.match(source, /--mode", "rpc"/);
  assert.match(source, /flutter[^\n]+run/);
  assert.match(source, /child\.kill\("SIGTERM"\)/);
  assert.match(source, /Core widget .* cannot be uninstalled/);
});

test('board config parsing validates column blocks', () => {
  const config = parseBoardConfig('# board\n\ncolumn todo:\n  name: To Do\n  label: status:todo\n\ncolumn doing:\n  name: Doing\n  label: status:doing\n\ncolumn shipped:\n  name: Shipped\n  state: closed\n');
  assert.deepEqual(config.columns.map(({id, name}) => ({id, name})), [
    {id: 'todo', name: 'To Do'},
    {id: 'doing', name: 'Doing'},
    {id: 'shipped', name: 'Shipped'},
  ]);
  assert.equal(config.columns[2].state, 'closed');
  assert.equal(config.columns[0].label, 'status:todo');
  assert.throws(() => parseBoardConfig('column todo:\n  name: To Do\ncolumn todo:\n  name: Twice\n'), /Duplicate column id/);
  assert.throws(() => parseBoardConfig('column todo:\n  label: status:todo\n'), /missing a name/);
  assert.throws(() => parseBoardConfig('column todo:\n  name: To Do\n  state: maybe\n'), /Invalid column state/);
  assert.throws(() => parseBoardConfig('column todo:\n  name: To Do\n  status: sometimes\n'), /Invalid column status rule/);
  assert.throws(() => parseBoardConfig('name: orphan\n'), /must follow a column header/);
  assert.throws(() => parseBoardConfig('# only comments\n'), /at least one column/);
});

test('default board derives columns from state and status labels', () => {
  const config = defaultBoardConfig();
  assert.equal(columnForCard([], 'open', config), 'backlog');
  assert.equal(columnForCard(['status:in-progress'], 'open', config), 'in_progress');
  assert.equal(columnForCard(['status:blocked'], 'open', config), 'in_progress');
  assert.equal(columnForCard(['task', 'status:review'], 'open', config), 'in_progress');
  assert.equal(columnForCard([], 'closed', config), 'done');
  assert.equal(columnForCard(['status:in-progress'], 'closed', config), 'done');
});

test('gh issue normalization detects types and caps bodies', () => {
  const config = defaultBoardConfig();
  const epic = normalizeGhIssue({number: 10, title: 'Epic: widgets', state: 'OPEN', labels: [{name: 'epic'}, {name: 'planning'}], body: '# Body', updatedAt: '2026-08-23T01:00:00Z', url: 'u10'}, config);
  assert.equal(epic.type, 'epic');
  assert.equal(epic.state, 'open');
  assert.equal(epic.column, 'backlog');
  const task = normalizeGhIssue({number: 11, title: 'Task: build', state: 'open', labels: [{name: 'task'}, {name: 'status:in-progress'}], body: 'x'.repeat(25_000), updatedAt: '2026-08-23T02:00:00Z', url: 'u11'}, config);
  assert.equal(task.type, 'task');
  assert.equal(task.column, 'in_progress');
  assert.equal(task.body.length, 20_000);
  const closed = normalizeGhIssue({number: 12, title: 'Done thing', state: 'CLOSED', labels: [], body: '', updatedAt: '2026-08-22T00:00:00Z', url: 'u12'}, config);
  assert.equal(closed.state, 'closed');
  assert.equal(closed.column, 'done');
  const plain = normalizeGhIssue({number: 13, title: 'Plain issue'}, config);
  assert.equal(plain.type, 'issue');
  assert.deepEqual(plain.labels, []);
});

test('planned tracker moves map columns to label and state mutations', () => {
  const config = parseBoardConfig('column todo:\n  name: To Do\n  label: status:todo\n\ncolumn doing:\n  name: Doing\n  label: status:doing\n\ncolumn shipped:\n  name: Shipped\n  state: closed\n');
  const card = {number: 11, title: 'Task', type: 'task', state: 'open', labels: ['task', 'status:todo'], body: '', updatedAt: '', url: '', column: 'todo'};
  assert.deepEqual(plannedTrackerMove(card, config.columns[1]), {add: ['status:doing'], remove: ['status:todo'], state: 'open'});
  assert.deepEqual(plannedTrackerMove(card, config.columns[0]), {add: [], remove: [], state: 'open'});
  assert.deepEqual(plannedTrackerMove(card, config.columns[2]), {add: [], remove: ['status:todo'], state: 'closed'});
});

function stubRunner(responses) {
  const calls = [];
  const runner = (command, args) => {
    calls.push({command, args});
    for (const response of responses) if (response.match(command, args)) return {status: response.status ?? 0, stdout: response.stdout ?? '', stderr: response.stderr ?? ''};
    return {status: 0, stdout: '', stderr: ''};
  };
  runner.calls = calls;
  return runner;
}

const ghIssuesFixture = [
  {number: 10, title: 'Epic: widgets', state: 'OPEN', labels: [{name: 'epic'}, {name: 'planning'}], body: '# Epic body', updatedAt: '2026-08-23T01:00:00Z', url: 'https://github.com/acme/widgets/issues/10'},
  {number: 11, title: 'Task: build', state: 'open', labels: [{name: 'task'}, {name: 'status:todo'}], body: 'Task body', updatedAt: '2026-08-23T02:00:00Z', url: 'https://github.com/acme/widgets/issues/11'},
  {number: 12, title: 'Done thing', state: 'closed', labels: [], body: '', updatedAt: '2026-08-22T00:00:00Z', url: 'https://github.com/acme/widgets/issues/12'},
];

function onlineRunner() {
  return stubRunner([
    {match: (command) => command === 'git', stdout: 'https://github.com/acme/widgets.git\n'},
    {match: (command, args) => command === 'gh' && args[1] === 'list', stdout: JSON.stringify(ghIssuesFixture)},
  ]);
}

test('tracker sync refreshes via gh, caches offline, and reloads the cache', async () => {
  const workspace = tempDir('pif-tracker-');
  const boards = [];
  const tracker = new TrackerSync(workspace, (state) => boards.push(state), onlineRunner(), true);
  await tracker.init();
  assert.equal(tracker.state.cards.length, 0);
  const refreshed = tracker.refresh();
  assert.equal(refreshed.ok, true);
  assert.equal(tracker.state.repo, 'acme/widgets');
  assert.deepEqual(tracker.state.columns.map((column) => column.id), ['backlog', 'in_progress', 'done']);
  assert.equal(tracker.state.cards.length, 3);
  assert.equal(tracker.state.stale, false);
  assert.ok(fs.existsSync(path.join(workspace, '.pi', 'pif', 'cache', 'tracker-cache.json')));
  const listed = tracker.list();
  assert.ok(listed.cards.every((card) => !('body' in card)));
  assert.equal(boards.length, 1);

  const offline = new TrackerSync(workspace, () => {}, stubRunner([
    {match: (command) => command === 'git', stdout: 'https://github.com/acme/widgets.git\n'},
    {match: (command, args) => command === 'gh' && args[1] === 'list', status: 1, stderr: 'gh: authentication required'},
  ]), true);
  await offline.init();
  assert.equal(offline.state.cards.length, 3);
  assert.equal(offline.state.stale, true);
  const failed = offline.refresh();
  assert.equal(failed.ok, false);
  assert.match(offline.state.error, /authentication required/);
  assert.equal(offline.state.cards.length, 3);
  fs.rmSync(workspace, {recursive: true, force: true});
});

test('tracker move writes back through gh and reverts nothing on failure', async () => {
  const workspace = tempDir('pif-tracker-');
  fs.mkdirSync(path.join(workspace, '.pif'), {recursive: true});
  fs.writeFileSync(path.join(workspace, '.pif', 'board.yaml'), 'column todo:\n  name: To Do\n  label: status:todo\n\ncolumn doing:\n  name: Doing\n  label: status:doing\n\ncolumn shipped:\n  name: Shipped\n  state: closed\n');
  const runner = onlineRunner();
  const tracker = new TrackerSync(workspace, () => {}, runner, true);
  await tracker.init();
  tracker.refresh();

  const moved = tracker.move({number: 11, column: 'doing'});
  assert.equal(moved.ok, true);
  const edit = runner.calls.find((call) => call.args[1] === 'edit');
  assert.deepEqual(edit.args, ['issue', 'edit', '11', '-R', 'acme/widgets', '--add-label', 'status:doing', '--remove-label', 'status:todo']);
  const card = tracker.state.cards.find((candidate) => candidate.number === 11);
  assert.deepEqual(card.labels, ['task', 'status:doing']);
  assert.equal(card.column, 'doing');

  const shipped = tracker.move({number: 11, column: 'shipped'});
  assert.equal(shipped.ok, true);
  const flip = runner.calls.filter((call) => call.args[1] !== 'list').pop();
  assert.deepEqual(flip.args, ['issue', 'close', '11', '-R', 'acme/widgets']);
  assert.equal(card.state, 'closed');
  assert.equal(card.column, 'shipped');

  const rejected = tracker.move({number: 404, column: 'doing'});
  assert.equal(rejected.ok, false);
  assert.match(rejected.error, /Unknown card/);

  const failing = new TrackerSync(workspace, () => {}, stubRunner([
    {match: (command) => command === 'git', stdout: 'https://github.com/acme/widgets.git\n'},
    {match: (command, args) => command === 'gh' && args[1] === 'list', stdout: JSON.stringify(ghIssuesFixture)},
    {match: (command, args) => command === 'gh' && args[1] === 'edit', status: 1, stderr: 'gh: label does not exist'},
  ]), true);
  await failing.init();
  failing.refresh();
  const failed = failing.move({number: 11, column: 'doing'});
  assert.equal(failed.ok, false);
  assert.match(failed.error, /label does not exist/);
  const unchanged = failing.state.cards.find((candidate) => candidate.number === 11);
  assert.equal(unchanged.column, 'todo');
  assert.deepEqual(unchanged.labels, ['task', 'status:todo']);
  fs.rmSync(workspace, {recursive: true, force: true});
});

test('tracker create writes through gh, falls back without labels, and prepends the card', async () => {
  const workspace = tempDir('pif-tracker-');
  fs.mkdirSync(path.join(workspace, '.pif'), {recursive: true});
  fs.writeFileSync(path.join(workspace, '.pif', 'board.yaml'), 'column todo:\n  name: To Do\n  label: status:todo\ncolumn doing:\n  name: Doing\n  label: status:doing\ncolumn shipped:\n  name: Shipped\n  state: closed\n');
  const runner = stubRunner([
    {match: (command) => command === 'git', stdout: 'git@github.com:acme/widgets.git\n'},
    {match: (command, args) => command === 'gh' && args[0] === 'issue' && args[1] === 'list', stdout: JSON.stringify(ghIssuesFixture)},
    {match: (command, args) => command === 'gh' && args[1] === 'create' && args.includes('status:todo'), status: 1, stderr: "could not add label: 'status:todo' not found"},
    {match: (command, args) => command === 'gh' && args[1] === 'create', stdout: 'https://github.com/acme/widgets/issues/20\n'},
  ]);
  const tracker = new TrackerSync(workspace, () => {}, runner, true);
  await tracker.init();
  tracker.refresh();
  const missingTitle = tracker.create({body: 'no title'});
  assert.equal(missingTitle.ok, false);
  assert.match(missingTitle.error, /Title is required/);
  const badColumn = tracker.create({title: 'X', column: 'nowhere'});
  assert.equal(badColumn.ok, false);
  assert.match(badColumn.error, /Unknown column/);
  const created = tracker.create({title: 'New ticket', body: 'Body text', type: 'task', column: 'todo'});
  assert.equal(created.ok, true);
  assert.equal(created.number, 20);
  const createArgs = runner.calls.filter((call) => call.args[1] === 'create');
  assert.equal(createArgs.length, 2);
  assert.ok(createArgs[0].args.includes('status:todo'));
  assert.ok(!createArgs[1].args.includes('--label'));
  const card = tracker.state.cards.find((candidate) => candidate.number === 20);
  assert.equal(card.title, 'New ticket');
  assert.equal(card.type, 'task');
  assert.equal(card.column, 'todo');
  assert.equal(tracker.state.cards[0].number, 20);
  fs.rmSync(workspace, {recursive: true, force: true});
});

test('tracker update edits title and body through gh and patches locally', async () => {
  const workspace = tempDir('pif-tracker-');
  const runner = onlineRunner();
  const tracker = new TrackerSync(workspace, () => {}, runner, true);
  await tracker.init();
  tracker.refresh();
  const empty = tracker.update({number: 11, title: '  '});
  assert.equal(empty.ok, false);
  assert.match(empty.error, /Title cannot be empty/);
  const nothing = tracker.update({number: 11});
  assert.equal(nothing.ok, false);
  const unknown = tracker.update({number: 999, title: 'x'});
  assert.equal(unknown.ok, false);
  const updated = tracker.update({number: 11, title: 'Task: renamed', body: 'New body'});
  assert.equal(updated.ok, true);
  const edit = runner.calls.filter((call) => call.args[1] === 'edit').pop();
  assert.deepEqual(edit.args, ['issue', 'edit', '11', '-R', 'acme/widgets', '--title', 'Task: renamed', '--body', 'New body']);
  const card = tracker.state.cards.find((candidate) => candidate.number === 11);
  assert.equal(card.title, 'Task: renamed');
  assert.equal(card.body, 'New body');
  fs.rmSync(workspace, {recursive: true, force: true});
});

test('tracker delete removes the card through gh and keeps state on failure', async () => {
  const workspace = tempDir('pif-tracker-');
  const failing = stubRunner([
    {match: (command) => command === 'git', stdout: 'https://github.com/acme/widgets.git\n'},
    {match: (command, args) => command === 'gh' && args[1] === 'list', stdout: JSON.stringify(ghIssuesFixture)},
    {match: (command, args) => command === 'gh' && args[1] === 'delete', status: 1, stderr: 'gh: no delete permission'},
  ]);
  const tracker = new TrackerSync(workspace, () => {}, failing, true);
  await tracker.init();
  tracker.refresh();
  const failed = tracker.delete({number: 11});
  assert.equal(failed.ok, false);
  assert.match(failed.error, /no delete permission/);
  assert.ok(tracker.state.cards.some((candidate) => candidate.number === 11));

  const runner = onlineRunner();
  const working = new TrackerSync(workspace, () => {}, runner, true);
  await working.init();
  working.refresh();
  const removed = working.delete({number: 11});
  assert.equal(removed.ok, true);
  const deleteCall = runner.calls.filter((call) => call.args[1] === 'delete').pop();
  assert.deepEqual(deleteCall.args, ['issue', 'delete', '11', '-R', 'acme/widgets', '--yes']);
  assert.ok(!working.state.cards.some((candidate) => candidate.number === 11));
  fs.rmSync(workspace, {recursive: true, force: true});
});

test('tracker surfaces invalid board config and missing github remote as errors', async () => {
  const workspace = tempDir('pif-tracker-');
  fs.mkdirSync(path.join(workspace, '.pif'), {recursive: true});
  fs.writeFileSync(path.join(workspace, '.pif', 'board.yaml'), 'column broken:\n  state: sideways\n');
  const invalid = new TrackerSync(workspace, () => {}, onlineRunner(), true);
  await invalid.init();
  const result = invalid.refresh();
  assert.equal(result.ok, false);
  assert.match(invalid.state.error, /Invalid board\.yaml/);

  const remoteless = new TrackerSync(tempDir('pif-tracker-'), () => {}, stubRunner([
    {match: (command) => command === 'git', status: 1, stderr: 'fatal: no such remote'},
  ]), true);
  await remoteless.init();
  const noRepo = remoteless.refresh();
  assert.equal(noRepo.ok, false);
  assert.match(remoteless.state.error, /no GitHub origin remote/);
  fs.rmSync(workspace, {recursive: true, force: true});
});

// ---------------------------------------------------------------------------
// Layered widget sources (#155): base app -> global catalog -> project overlay
// ---------------------------------------------------------------------------

function writeWidgetFixture(root, id, overrides = {}) {
  const dir = path.join(root, id);
  fs.mkdirSync(dir, {recursive: true});
  const fields = {slot: 'center', core: 'false', name: `${id} name`, ...overrides};
  fs.writeFileSync(path.join(dir, 'widget.yaml'), `id: ${id}\nname: "${fields.name}"\nversion: 0.1.0\ndescription: "Layered fixture"\nslot: ${fields.slot}\ncore: ${fields.core}\ntags: [test]\ndart_dependencies: []\n`);
  fs.writeFileSync(path.join(dir, `${id}.dart`), `// ${id} fixture source\n`);
  return dir;
}

/** Clean non-repo workspace + app dir + global catalog, all temp dirs, wired
 * through env overrides (this is the #130 "install once, use in any project"
 * shape: the app never has to live inside the workspace). */
function layeredFixture(t) {
  const workspace = tempDir('pif-layered-ws-');
  const appDir = tempDir('pif-layered-app-');
  const globalCatalog = tempDir('pif-layered-global-');
  fs.mkdirSync(path.join(appDir, 'lib', 'widgets'), {recursive: true});
  fs.mkdirSync(path.join(appDir, 'catalog'), {recursive: true});
  const previousAppDir = process.env.PIF_APP_DIR;
  const previousGlobalCatalog = process.env.PIF_GLOBAL_CATALOG;
  process.env.PIF_APP_DIR = appDir;
  process.env.PIF_GLOBAL_CATALOG = globalCatalog;
  t.after(() => {
    if (previousAppDir === undefined) delete process.env.PIF_APP_DIR; else process.env.PIF_APP_DIR = previousAppDir;
    if (previousGlobalCatalog === undefined) delete process.env.PIF_GLOBAL_CATALOG; else process.env.PIF_GLOBAL_CATALOG = previousGlobalCatalog;
    for (const dir of [workspace, appDir, globalCatalog]) fs.rmSync(dir, {recursive: true, force: true});
  });
  return {workspace, appDir, globalCatalog};
}

function layeredHub(workspace) {
  return new __pif.PifHub({}, {}, workspace, 0);
}

test('layered widget sources resolve deterministically with provenance (#155)', async (t) => {
  const f = layeredFixture(t);
  writeWidgetFixture(path.join(f.appDir, 'lib', 'widgets'), 'alpha_widget', {core: 'true'});
  writeWidgetFixture(path.join(f.appDir, 'lib', 'widgets'), 'shared_widget', {name: 'Base Shared'});
  writeWidgetFixture(path.join(f.appDir, 'catalog'), 'archived_widget');
  writeWidgetFixture(path.join(f.appDir, 'catalog'), 'catalog_shadow', {name: 'Archive Shadow'});
  writeWidgetFixture(f.globalCatalog, 'global_only');
  writeWidgetFixture(f.globalCatalog, 'catalog_shadow', {name: 'Global Shadow'});
  writeWidgetFixture(path.join(f.workspace, 'pif_app', 'widgets'), 'shared_widget', {name: 'Project Shared'});
  writeWidgetFixture(path.join(f.workspace, 'pif_app', 'widgets'), 'project_only');
  const hub = layeredHub(f.workspace);
  assert.equal(hub.appDir, f.appDir, 'PIF_APP_DIR pins the base app outside the workspace');
  assert.equal(hub.globalCatalogPath, f.globalCatalog);

  hub.loadRegistryState();
  hub.scanWidgets();
  // Wholesale shadowing: project wins over base for shared_widget.
  assert.deepEqual(Object.keys(hub.state.widgets).sort(), ['alpha_widget', 'project_only', 'shared_widget']);
  assert.equal(hub.state.widgets.shared_widget.source, 'project');
  assert.equal(hub.state.widgets.shared_widget.name, 'Project Shared', 'the later layer shadows the earlier id wholesale');
  assert.equal(hub.state.widgets.alpha_widget.source, 'base');
  assert.equal(hub.state.widgets.alpha_widget.enabled, true, 'core base widgets stay enabled');
  assert.equal(hub.state.widgets.project_only.source, 'project');
  // Catalog layer: global catalog entries shadow app-archive entries on the same id.
  assert.deepEqual(Object.keys(hub.state.catalog).sort(), ['archived_widget', 'catalog_shadow', 'global_only']);
  assert.equal(hub.state.catalog.archived_widget.source, 'base');
  assert.equal(hub.state.catalog.catalog_shadow.source, 'catalog');
  assert.equal(hub.state.catalog.catalog_shadow.name, 'Global Shadow');
  assert.equal(hub.state.catalog.global_only.source, 'catalog');
  assert.equal(hub.state.catalog.global_only.installed, false);

  // Determinism: widget.list rescans and must surface the identical resolved set.
  const first = JSON.stringify({widgets: hub.state.widgets, catalog: hub.state.catalog});
  const listed = await hub.control('widget.list');
  assert.equal(JSON.stringify({widgets: listed.installed, catalog: listed.catalog}), first);
  // Provenance flows through the snapshot the shell renders.
  const snap = hub.snapshot();
  assert.equal(snap.widgets.shared_widget.source, 'project');
  assert.equal(snap.catalog.global_only.source, 'catalog');
});

test('registry codegen carries provenance and project import paths (#155)', () => {
  const base = {...parseWidgetManifest(manifest), source: 'base'};
  const project = {...parseWidgetManifest(manifest.replace('alpha_widget', 'beta_page')), source: 'project', importPath: 'file:///ws/pif_app/widgets/beta_page/beta_page.dart'};
  const actual = generateWidgetRegistry([project, base]);
  assert.equal(actual, `// GENERATED BY pif. DO NOT EDIT.\nimport 'core/plugin.dart';\nimport 'widgets/alpha_widget/alpha_widget.dart';\nimport 'file:///ws/pif_app/widgets/beta_page/beta_page.dart';\n\nMap<String, PifWidgetPlugin Function()> pifWidgetFactories() {\n  return {\n    // source: base\n    'alpha_widget': () => AlphaWidgetPlugin(),\n    // source: project\n    'beta_page': () => BetaPagePlugin(),\n  };\n}\n`);
  assert.equal(dartFileUri('/tmp/some ws/pif_app/widgets/x/x.dart').startsWith('file://'), true);
  assert.throws(() => dartFileUri("/tmp/qu'ote/x.dart"), /Unsafe Dart import URI/);
  assert.throws(() => generateWidgetRegistry([{...base, importPath: 'has space.dart'}]), /Unsafe registry import path/);
  assert.throws(() => generateWidgetRegistry([{...base, importPath: '/abs/x.dart'}]), /Unsafe registry import path/);
});

class StubbedAnalyzeHub extends __pif.PifHub {
  analyzeWidget() { return {ok: true, diagnostics: 'stub-clean'}; }
}

test('project widgets install in place and global catalog installs copy into the overlay (#155)', async (t) => {
  const f = layeredFixture(t);
  writeWidgetFixture(path.join(f.appDir, 'lib', 'widgets'), 'alpha_widget');
  writeWidgetFixture(path.join(f.appDir, 'catalog'), 'archived_widget');
  writeWidgetFixture(f.globalCatalog, 'global_only');
  const projectDir = writeWidgetFixture(path.join(f.workspace, 'pif_app', 'widgets'), 'project_only');
  const projectShared = writeWidgetFixture(path.join(f.workspace, 'pif_app', 'widgets'), 'shared_widget', {name: 'Project Shared'});
  writeWidgetFixture(path.join(f.appDir, 'lib', 'widgets'), 'shared_widget', {name: 'Base Shared'});
  const hub = new StubbedAnalyzeHub({}, {}, f.workspace, 0);
  hub.loadRegistryState();
  hub.scanWidgets();

  const result = await hub.installWidget({id: 'project_only'});
  assert.equal(result.ok, true);
  assert.equal(result.source, 'project');
  assert.ok(fs.existsSync(path.join(projectDir, 'widget.yaml')), 'project source never moves');
  assert.ok(!fs.existsSync(path.join(f.appDir, 'lib', 'widgets', 'project_only')), 'no copy escapes into the base app');
  assert.equal(hub.state.widgets.project_only.enabled, true);
  const registry = fs.readFileSync(path.join(f.appDir, 'lib', 'widget_registry.g.dart'), 'utf8');
  assert.match(registry, /\/\/ source: project\n    'project_only'/);
  assert.match(registry, new RegExp(`import 'file://${projectDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/project_only\\.dart';`));

  // Shadowed base ids install the project definition, in place.
  const shadowInstall = await hub.installWidget({id: 'shared_widget'});
  assert.equal(shadowInstall.source, 'project');
  assert.equal(hub.state.widgets.shared_widget.name, 'Project Shared');
  assert.ok(fs.existsSync(projectShared));

  // Global catalog install copies into the project overlay; the catalog source stays put.
  const globalInstall = await hub.installWidget({id: 'global_only'});
  assert.equal(globalInstall.ok, true);
  assert.equal(globalInstall.source, 'project');
  assert.ok(fs.existsSync(path.join(f.workspace, 'pif_app', 'widgets', 'global_only', 'widget.yaml')), 'global catalog installs copy into the project overlay');
  assert.ok(fs.existsSync(path.join(f.globalCatalog, 'global_only', 'widget.yaml')), 'global catalog source never moves');
  assert.equal(hub.state.widgets.global_only.source, 'project');
  assert.equal(hub.state.catalog.global_only, undefined);

  // App-archive installs keep the existing copy-into-base behaviour.
  const archiveInstall = await hub.installWidget({id: 'archived_widget'});
  assert.equal(archiveInstall.source, 'base');
  assert.ok(fs.existsSync(path.join(f.appDir, 'lib', 'widgets', 'archived_widget', 'widget.yaml')));
  assert.equal(hub.state.widgets.archived_widget.source, 'base');

  await assert.rejects(() => hub.installWidget({id: 'missing_widget'}), /not found in widgets or catalog/);
  await assert.rejects(() => hub.installWidget({id: '../escape'}), /snake_case/);
  // Writes stayed inside the declared roots: the workspace only gained the overlay and hub state.
  assert.deepEqual(fs.readdirSync(f.workspace).sort(), ['.pi', 'pif_app']);
});

test('project uninstall deregisters only; base uninstall archives; core refuses (#155)', async (t) => {
  const f = layeredFixture(t);
  writeWidgetFixture(path.join(f.appDir, 'lib', 'widgets'), 'core_widget', {core: 'true'});
  writeWidgetFixture(path.join(f.appDir, 'lib', 'widgets'), 'base_widget');
  const projectDir = writeWidgetFixture(path.join(f.workspace, 'pif_app', 'widgets'), 'project_only');
  const hub = new StubbedAnalyzeHub({}, {}, f.workspace, 0);
  hub.loadRegistryState();
  hub.scanWidgets();
  await hub.installWidget({id: 'project_only'});
  await hub.installWidget({id: 'base_widget'});
  assert.match(fs.readFileSync(path.join(f.appDir, 'lib', 'widget_registry.g.dart'), 'utf8'), /'project_only'/);

  const removed = await hub.uninstallWidget({id: 'project_only'});
  assert.equal(removed.ok, true);
  assert.equal(removed.source, 'project');
  assert.equal(removed.deregistered, true);
  assert.ok(fs.existsSync(path.join(projectDir, 'project_only.dart')), 'uninstalling a project widget keeps its source in place');
  assert.equal(hub.state.widgets.project_only.enabled, false, 'deregistered project widget stays present but disabled');
  assert.ok(!fs.readFileSync(path.join(f.appDir, 'lib', 'widget_registry.g.dart'), 'utf8').includes("'project_only'"), 'registry drops the deregistered widget');
  assert.equal(hub.state.catalog.project_only, undefined);

  const archived = await hub.uninstallWidget({id: 'base_widget'});
  assert.equal(archived.source, 'base');
  assert.ok(fs.existsSync(path.join(f.appDir, 'catalog', 'base_widget', 'widget.yaml')), 'base widgets archive to the app-local catalog');
  assert.ok(!fs.existsSync(path.join(f.appDir, 'lib', 'widgets', 'base_widget')));
  assert.equal(hub.state.catalog.base_widget.source, 'base');

  await assert.rejects(() => hub.uninstallWidget({id: 'core_widget'}), /Core widget .* cannot be uninstalled/);
  await assert.rejects(() => hub.uninstallWidget({id: 'never_was'}), /Unknown installed widget/);
});

// --- #188: tracker parent index + card excerpt ---

test('trackerParentRef binds tasks to their sprint, else epic; ambiguity resolves to null', () => {
  const body = '### Reference Index\n- **Epic**: #152 · **Sprint**: #153 (slotted before #157)\n\n## Task\nDo the thing.';
  assert.equal(trackerParentRef(body, 'task'), 153);
  const epicOnly = '### Reference Index\n- **Epic**: #152\n\n## Task\nGo.';
  assert.equal(trackerParentRef(epicOnly, 'task'), 152);
  assert.equal(trackerParentRef(epicOnly, 'sprint'), 152);
  const ambiguous = 'Epic: #152\nEpic: #155\nSprint: #1\nSprint: #2';
  assert.equal(trackerParentRef(ambiguous, 'task'), null);
  assert.equal(trackerParentRef(ambiguous, 'sprint'), null);
  assert.equal(trackerParentRef('No references at all', 'task'), null);
  assert.equal(trackerParentRef('Epic: #10', 'epic'), null);
  assert.equal(trackerParentRef('anything', 'issue'), null);
});

test('trackerExcerpt strips markdown, skips Reference Index, caps with ellipsis', () => {
  const body = '### Reference Index\n- **Epic**: #152 · **Sprint**: #153\n\n## Task\nGive the tracker board an **epic drill-down** so work is viewed per-epic.\n\n## Atomicity\n- Complexity score: 4.0';
  const excerpt = trackerExcerpt(body);
  assert.ok(excerpt.startsWith('Give the tracker board'), excerpt);
  assert.ok(!excerpt.includes('Reference Index'), excerpt);
  assert.ok(!excerpt.includes('**'), excerpt);
  assert.equal(trackerExcerpt('Plain task body'), 'Plain task body');
  assert.equal(trackerExcerpt(''), '');
  const long = trackerExcerpt('word '.repeat(200).trim(), 240);
  assert.ok(long.length <= 241, `${long.length}`);
  assert.ok(long.endsWith('…'));
});

test('plannedLabelChange diffs tags while preserving status and type labels', () => {
  const plan = plannedLabelChange(['task', 'status:todo', 'old-tag'], ['task', 'status:todo', 'new-tag'], 'task');
  assert.deepEqual(plan.add, ['new-tag']);
  assert.deepEqual(plan.remove, ['old-tag']);
  const none = plannedLabelChange(['task', 'status:todo'], ['task', 'status:todo'], 'task');
  assert.deepEqual(none.add, []);
  assert.deepEqual(none.remove, []);
  const protect = plannedLabelChange(['task', 'status:in-progress'], ['design'], 'task');
  assert.deepEqual(protect.add, ['design']);
  assert.deepEqual(protect.remove, []);
});

test('parseAppManifest accepts block and inline list forms with s-prefixed ids', () => {
  const good = parseAppManifest('id: notes\nname: Notes\nversion: 0.1.0\nhome: settings\npages:\n  - settings\n  - search\n  - ss_panel\ntemplate: mercury\ndependencies:\n  - search_index\n  - ss_catalog\n');
  assert.equal(good.error, undefined);
  assert.deepEqual(good.manifest, { id: 'notes', name: 'Notes', version: '0.1.0', home: 'settings', pages: ['settings', 'search', 'ss_panel'], template: 'mercury', dependencies: ['search_index', 'ss_catalog'] });
  const inline = parseAppManifest('id: notes\nname: Notes\nhome: settings\npages: [settings, search, ss_panel]\ndependencies: [search_index, ss_catalog]\n');
  assert.deepEqual(inline.manifest, { id: 'notes', name: 'Notes', version: '0.1.0', home: 'settings', pages: ['settings', 'search', 'ss_panel'], template: undefined, dependencies: ['search_index', 'ss_catalog'] });
  assert.deepEqual(parseAppManifest(renderAppManifest(good.manifest)).manifest, good.manifest);
  assert.deepEqual(parseAppManifest(renderAppManifest(inline.manifest)).manifest, { ...inline.manifest, template: undefined });
  assert.match(parseAppManifest('id: Bad Id\nname: X\nhome: a\npages: [a]').error, /kebab identifier/);
  assert.match(parseAppManifest('id: notes\nhome: home\npages: [home]').error, /'name' is required/);
  assert.match(parseAppManifest('id: notes\nname: N\nhome: editor\npages: [home]').error, /'home' must be one of the declared pages/);
  assert.match(parseAppManifest('id: notes\nname: N\nhome: settings\npages: [settings, settings]').error, /duplicate/);
  assert.match(parseAppManifest('id: notes\nname: N\nhome: settings\npages: [settings]\ntemplate: not valid template!\n').error, /template/);
  assert.match(parseAppManifest('what is this line\n', ).error, /line 1/);
});

test('app manifest updates validate and render round-trips', () => {
  const base = parseAppManifest('id: notes\nname: Notes\nhome: settings\npages: [settings]\ndependencies: [search_index]\n').manifest;
  const withPage = addAppPage(base, 'search');
  assert.deepEqual(withPage.manifest.pages, ['settings', 'search']);
  assert.match(addAppPage(base, 'settings').error, /already declared/);
  assert.match(addAppPage(base, 'Not Kebab').error, /widget identifier/);
  const newHome = setAppHome(withPage.manifest, 'search');
  assert.equal(newHome.manifest.home, 'search');
  assert.match(setAppHome(withPage.manifest, 'missing').error, /must be one of the declared pages/);
  assert.equal(slugifyAppId('My Fancy App!'), 'my-fancy-app');
  const rendered = renderAppManifest(newHome.manifest);
  const reparsed = parseAppManifest(rendered);
  assert.equal(reparsed.error, undefined);
  assert.deepEqual(reparsed.manifest, newHome.manifest);
});

test('pif_app.build publishes correlated build_result envelopes and stays responsive (#192)', async () => {
  const workspace = tempDir('pif-build-');
  const appDir = tempDir('pif-build-app-');
  const globalCatalog = tempDir('pif-build-catalog-');
  const modelsPath = path.join(workspace, '.pi', 'agent', 'models.json');
  const agentDir = path.join(workspace, '.pi', 'agent');
  const previousEnv = {
    PIF_APP_DIR: process.env.PIF_APP_DIR,
    PIF_GLOBAL_CATALOG: process.env.PIF_GLOBAL_CATALOG,
    PIF_MODELS_PATH: process.env.PIF_MODELS_PATH,
    PI_CODING_AGENT_DIR: process.env.PI_CODING_AGENT_DIR,
  };
  fs.mkdirSync(path.join(agentDir, 'agents'), {recursive: true});
  fs.mkdirSync(path.join(agentDir, 'extensions'), {recursive: true});
  fs.mkdirSync(path.join(agentDir, 'state'), {recursive: true});
  fs.mkdirSync(appDir, {recursive: true});
  fs.mkdirSync(globalCatalog, {recursive: true});
  fs.writeFileSync(path.join(appDir, 'pubspec.yaml'), 'name: pif_build_app\n');
  fs.writeFileSync(modelsPath, JSON.stringify({providers: {}}, null, 2) + '\n');
  const peerMessages = [];
  const peer = { sendRaw(payload) { peerMessages.push(JSON.parse(Buffer.from(payload).toString())); }, close() {} };
  const { harness, restore } = patchBuildSpawn([
    {kind: 'child'},
    {kind: 'child'},
    {kind: 'error', message: 'spawn failed asynchronously', code: 127},
    {kind: 'throw', message: 'spawn denied by fixture'},
  ]);
  let hub;
  try {
    process.env.PIF_APP_DIR = appDir;
    process.env.PIF_GLOBAL_CATALOG = globalCatalog;
    process.env.PIF_MODELS_PATH = modelsPath;
    process.env.PI_CODING_AGENT_DIR = agentDir;
    hub = new __pif.PifHub({}, { ui: { setStatus() {}, notify() {} }, model: { id: 'fixture-model' }, thinkingLevel: 'low' }, workspace, 0);
    hub.state.app = parseAppManifest('id: notes\nname: Notes\nhome: home\npages: [home]\ndependencies: []\n').manifest;
    hub.peers.add(peer);
    const buildScript = path.join(repo, 'scripts', 'build-pif-project-app.sh');
    // Fake children only: this checks the app/build contract, not real process cleanup.

    const success = hub.control('pif_app.build', { name: 'Exported App' });
    const successChild = harness.children[0];
    assert.equal(path.basename(harness.calls[0].command), path.basename(buildScript));
    assert.deepEqual(harness.calls[0].args, [workspace, 'Exported App']);
    successChild.emitSpawn();
    const successAck = await success;
    assert.equal(successAck.ok, true);
    assert.equal(successAck.started, true);
    assert.equal(successAck.name, 'Exported App');
    const statusDuringSuccess = await hub.control('shell.status');
    assert.equal(statusDuringSuccess.app.id, 'notes');
    const stdoutChunk = 'stdout-'.repeat(400);
    const stderrChunk = 'stderr-'.repeat(400);
    successChild.stdout.emit('data', stdoutChunk);
    successChild.stderr.emit('data', stderrChunk);
    successChild.emitClose(0);
    successChild.emitClose(0);
    await waitFor(() => peerMessages.length === 1, 'first build_result');
    assert.equal(peerMessages.length, 1);
    assert.equal(peerMessages[0].channel, 'app/build');
    assert.equal(peerMessages[0].type, 'build_result');
    assert.equal(peerMessages[0].payload.buildId, successAck.buildId);
    assert.equal(peerMessages[0].payload.name, 'Exported App');
    assert.equal(peerMessages[0].payload.ok, true);
    assert.equal(peerMessages[0].payload.code, 0);
    assert.equal(peerMessages[0].payload.output.length, 4000);
    assert.equal(peerMessages[0].payload.output, `${stdoutChunk}${stderrChunk}`.slice(-4000));

    const nonzero = hub.control('pif_app.build', { name: 'Broken App' });
    const nonzeroChild = harness.children[1];
    assert.deepEqual(harness.calls[1].args, [workspace, 'Broken App']);
    nonzeroChild.emitSpawn();
    const nonzeroAck = await nonzero;
    assert.equal(nonzeroAck.ok, true);
    const statusDuringFailure = await hub.control('shell.status');
    assert.equal(statusDuringFailure.app.id, 'notes');
    nonzeroChild.stdout.emit('data', 'warn ');
    nonzeroChild.emitClose(17);
    await waitFor(() => peerMessages.length === 2, 'second build_result');
    assert.equal(peerMessages[1].payload.buildId, nonzeroAck.buildId);
    assert.equal(peerMessages[1].payload.ok, false);
    assert.equal(peerMessages[1].payload.code, 17);
    assert.equal(peerMessages[1].payload.output, 'warn ');
    assert.equal(peerMessages[1].payload.error, undefined);

    const asyncError = await hub.control('pif_app.build', { name: 'Async Fail App' });
    assert.equal(harness.calls[2].args[1], 'Async Fail App');
    assert.equal(asyncError.ok, false);
    assert.equal(asyncError.started, false);
    assert.match(asyncError.error, /spawn failed asynchronously/);
    const statusAfterAsyncError = await hub.control('shell.status');
    assert.equal(statusAfterAsyncError.app.id, 'notes');
    await waitFor(() => peerMessages.length === 3, 'async-error build_result');
    assert.equal(peerMessages[2].payload.buildId, asyncError.buildId);
    assert.equal(peerMessages[2].payload.ok, false);
    assert.equal(peerMessages[2].payload.code, -1);
    assert.match(peerMessages[2].payload.error, /spawn failed asynchronously/);
    assert.equal(peerMessages[2].payload.output, '');

    const spawnError = await hub.control('pif_app.build', { name: 'Denied App' });
    assert.equal(harness.calls[3].args[1], 'Denied App');
    assert.equal(spawnError.ok, false);
    assert.equal(spawnError.started, false);
    assert.match(spawnError.error, /spawn denied by fixture/);
    const statusAfterError = await hub.control('shell.status');
    assert.equal(statusAfterError.app.id, 'notes');
    await waitFor(() => peerMessages.length === 4, 'spawn-error build_result');
    assert.equal(peerMessages[3].payload.buildId, spawnError.buildId);
    assert.equal(peerMessages[3].payload.ok, false);
    assert.equal(peerMessages[3].payload.code, -1);
    assert.match(peerMessages[3].payload.error, /spawn denied by fixture/);
    assert.equal(peerMessages[3].payload.output, '');
  } finally {
    if (hub) await hub.stop();
    restore();
    if (previousEnv.PIF_APP_DIR === undefined) delete process.env.PIF_APP_DIR; else process.env.PIF_APP_DIR = previousEnv.PIF_APP_DIR;
    if (previousEnv.PIF_GLOBAL_CATALOG === undefined) delete process.env.PIF_GLOBAL_CATALOG; else process.env.PIF_GLOBAL_CATALOG = previousEnv.PIF_GLOBAL_CATALOG;
    if (previousEnv.PIF_MODELS_PATH === undefined) delete process.env.PIF_MODELS_PATH; else process.env.PIF_MODELS_PATH = previousEnv.PIF_MODELS_PATH;
    if (previousEnv.PI_CODING_AGENT_DIR === undefined) delete process.env.PI_CODING_AGENT_DIR; else process.env.PI_CODING_AGENT_DIR = previousEnv.PI_CODING_AGENT_DIR;
    fs.rmSync(workspace, { recursive: true, force: true });
    fs.rmSync(appDir, { recursive: true, force: true });
    fs.rmSync(globalCatalog, { recursive: true, force: true });
  }
});
